In [35]:
import pandas as pd

df = pd.read_csv('C:/2019-20/DataScience/Data/pokemon_data.csv')
#df1 = pd.read_excel('pokemon_data.xlsx')
#df1 = pd.read_csv('pokemon_data.txt', delimiter='\t')
#print(df.head(3))
#print(df.tail(3))
#print(df.columns)
#print (df['Name'][0:5])
#print (df.iloc[1])
#print (df.iloc[1:4])
#print (df.iloc[2,1])
#for index, row in df.iterrows():
    #print (index, row)
#    print (index, row['Name'])
#df.loc[df['Type 1'] == "Fire"]
#df.describe()
#df.sort_values('Name', ascending = False)
#df.sort_values(['Type 1', 'HP'], ascending = [1,0])
#df['Total']= df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
#print (df.head(5))
#df['Total']= df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
#df=df.drop(columns= ['Total'])
# adding from col 4 to col 9 accroos the row specified by axis=1
df['Total']= df.iloc[:, 4:10].sum(axis=1)
#df= df[['Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]
cols = list(df.columns)
df = df[cols[0:4] + [cols[-1]]+cols[4:12]]
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

     Total  HP  Attack  Defense  Speed  Speed  Speed  Speed  Speed  Speed  \
0      270  45      49       49     45     45     45     45     45     45
1      360  60      62       63     60     60     60     60     60     60
2      480  80      82       83     80     80     80     80     80     80
3      480  80     100      123     80     80     80     80     80     80
4      390  39      52       43     65     65     65     65     65     65
..     ...  ..     ...      ...    ...    ...    ...    ...    ...    ...
795    300  50     100      150     50     50     50     50     50     50
796    660  50     160      110    110    110    110    110    110    110
797    420  80     110       60     70     70     70     70     70     70
798    480  80     160       60     80     80     80     80     80     80
799    420  80     110      120     70     70     70     70     70     70

     ...  Speed  Speed  Speed  Speed  Speed  Speed  Speed  Speed  Speed  Speed
0    ...     45     45     45     45     45     45     45     45     45     45
1    ...     60     60     60     60     60     60     60     60     60     60
2    ...     80     80     80     80     80     80     80     80     80     80
3    ...     80     80     80     80     80     80     80     80     80     80
4    ...     65     65     65     65     65     65     65     65     65     65
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
795  ...     50     50     50     50     50     50     50     50     50     50
796  ...    110    110    110    110    110    110    110    110    110    110
797  ...     70     70     70     70     70     70     70     70     70     70
798  ...     80     80     80     80     80     80     80     80     80     80
799  ...     70     70     70     70     70     70     70     70     70     70

[800 rows x 30622 columns]